package com.gmail.sacchin.pokemonbattleanalyzer;

import android.content.res.Resources;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.graphics.Matrix;
import android.util.Log;

import com.gmail.sacchin.pokemonbattleanalyzer.entity.PBAPokemon;

import java.util.HashMap;
import java.util.Map;

public class Util {
	public Map<String, Integer> pokemonImageResource = null;
	public Map<String, Integer> itemImageResource = null;

	public Util(){
		itemImageResource = new HashMap<>();
		itemImageResource.put("いのちのたま", R.drawable.lifeorb);
		itemImageResource.put("こだわりメガネ", R.drawable.choicespecs);
		itemImageResource.put("こだわりハチマキ", R.drawable.choiceband);
		itemImageResource.put("こだわりスカーフ", R.drawable.choicescarf);
//		itemImageResource.put("ものしりメガネ", R.drawable.);
//		itemImageResource.put("ちからのハチマキ", R.drawable.);
//		itemImageResource.put("たつじんのおび", R.drawable.);
//		itemImageResource.put("メトロノーム", R.drawable.);
		itemImageResource.put("あおぞらプレート", R.drawable.skyplate);
//		itemImageResource.put("いかずちプレート", R.drawable.);
//		itemImageResource.put("がんせきプレート", R.drawable.);
//		itemImageResource.put("こうてつプレート", R.drawable.);
//		itemImageResource.put("こぶしのプレート", R.drawable.);
//		itemImageResource.put("こわもてプレート", R.drawable.);
//		itemImageResource.put("しずくプレート", R.drawable.);
//		itemImageResource.put("だいちのプレート", R.drawable.);
//		itemImageResource.put("たまむしプレート", R.drawable.);
//		itemImageResource.put("つららのプレート", R.drawable.);
//		itemImageResource.put("ひのたまプレート", R.drawable.);
//		itemImageResource.put("ふしぎのプレート", R.drawable.);
//		itemImageResource.put("みどりのプレート", R.drawable.);
//		itemImageResource.put("もうどくプレート", R.drawable.);
//		itemImageResource.put("もののけプレート", R.drawable.);
//		itemImageResource.put("りゅうのプレート", R.drawable.);
//		itemImageResource.put("あくのジュエル", R.drawable.);
//		itemImageResource.put("いわのジュエル", R.drawable.);
//		itemImageResource.put("エスパージュエル", R.drawable.);
//		itemImageResource.put("かくとうジュエル", R.drawable.);
//		itemImageResource.put("くさのジュエル", R.drawable.);
//		itemImageResource.put("ゴーストジュエル", R.drawable.);
//		itemImageResource.put("こおりのジュエル", R.drawable.);
//		itemImageResource.put("じめんのジュエル", R.drawable.);
//		itemImageResource.put("でんきのジュエル", R.drawable.);
//		itemImageResource.put("どくのジュエル", R.drawable.);
//		itemImageResource.put("ドラゴンジュエル", R.drawable.);
//		itemImageResource.put("ノーマルジュエル", R.drawable.);
//		itemImageResource.put("はがねのジュエル", R.drawable.);
//		itemImageResource.put("ひこうのジュエル", R.drawable.);
//		itemImageResource.put("ほのおのジュエル", R.drawable.);
//		itemImageResource.put("みずのジュエル", R.drawable.);
//		itemImageResource.put("むしのジュエル", R.drawable.);
//		itemImageResource.put("あついいわ", R.drawable.);
		itemImageResource.put("しめったいわ", R.drawable.damprock);
//		itemImageResource.put("さらさらいわ", R.drawable.);
//		itemImageResource.put("つめたいいわ", R.drawable.);
//		itemImageResource.put("ひかりのねんど", R.drawable.);
//		itemImageResource.put("ねばりのかぎづめ", R.drawable.);
//		itemImageResource.put("きあいのタスキ", R.drawable.);
		itemImageResource.put("たべのこし", R.drawable.leftover);
//		itemImageResource.put("くろいヘドロ", R.drawable.);
//		itemImageResource.put("せんせいのツメ", R.drawable.);
//		itemImageResource.put("ピントレンズ", R.drawable.);
//		itemImageResource.put("するどいツメ", R.drawable.);
//		itemImageResource.put("のんきのおこう", R.drawable.);
		itemImageResource.put("ひかりのこな", R.drawable.brightpowder);
//		itemImageResource.put("こうかくレンズ", R.drawable.);
//		itemImageResource.put("フォーカスレンズ", R.drawable.);
//		itemImageResource.put("きれいなぬけがら", R.drawable.);
//		itemImageResource.put("おおきなねっこ", R.drawable.);
//		itemImageResource.put("かいがらのすず", R.drawable.);
//		itemImageResource.put("するどいキバ", R.drawable.);
//		itemImageResource.put("おうじゃのしるし", R.drawable.);
//		itemImageResource.put("しろいハーブ", R.drawable.);
		itemImageResource.put("パワフルハーブ", R.drawable.powerherb);
		itemImageResource.put("メンタルハーブ", R.drawable.mentalherb);
//		itemImageResource.put("クラボのみ", R.drawable.);
		itemImageResource.put("カゴのみ", R.drawable.chestoberry);
//		itemImageResource.put("モモンのみ", R.drawable.);
//		itemImageResource.put("チーゴのみ", R.drawable.);
//		itemImageResource.put("ナナシのみ", R.drawable.);
		itemImageResource.put("キーのみ", R.drawable.keeberry);
		itemImageResource.put("ラムのみ", R.drawable.lumberry);
		itemImageResource.put("オボンのみ", R.drawable.sitrusberry);
//		itemImageResource.put("ヒメリのみ", R.drawable.);
//		itemImageResource.put("チイラのみ", R.drawable.);
//		itemImageResource.put("リュガのみ", R.drawable.);
//		itemImageResource.put("カムラのみ", R.drawable.);
//		itemImageResource.put("ヤタピのみ", R.drawable.);
//		itemImageResource.put("ズアのみ", R.drawable.);
//		itemImageResource.put("サンのみ", R.drawable.);
//		itemImageResource.put("スターのみ", R.drawable.);
//		itemImageResource.put("ミクルのみ", R.drawable.);
//		itemImageResource.put("イバンのみ", R.drawable.);
//		itemImageResource.put("ナゾのみ", R.drawable.);
//		itemImageResource.put("ジャボのみ", R.drawable.);
//		itemImageResource.put("レンブのみ", R.drawable.);
		itemImageResource.put("オッカのみ", R.drawable.occaberry);
//		itemImageResource.put("イトケのみ", R.drawable.);
		itemImageResource.put("ソクノのみ", R.drawable.wacanberry);
		itemImageResource.put("リンドのみ", R.drawable.rindoberry);
		itemImageResource.put("ヤチェのみ", R.drawable.yacheberry);
		itemImageResource.put("ヨプのみ", R.drawable.chopleberry);
//		itemImageResource.put("ビアーのみ", R.drawable.);
		itemImageResource.put("シュカのみ", R.drawable.shucaberry);
//		itemImageResource.put("バコウのみ", R.drawable.);
//		itemImageResource.put("ウタンのみ", R.drawable.);
//		itemImageResource.put("タンガのみ", R.drawable.);
//		itemImageResource.put("ヨロギのみ", R.drawable.);
//		itemImageResource.put("カシブのみ", R.drawable.);
//		itemImageResource.put("ハバンのみ", R.drawable.);
//		itemImageResource.put("ナモのみ", R.drawable.);
//		itemImageResource.put("リリバのみ", R.drawable.);
//		itemImageResource.put("ホズのみ", R.drawable.);
//		itemImageResource.put("かえんだま", R.drawable.);
//		itemImageResource.put("どくどくだま", R.drawable.);
//		itemImageResource.put("こうこうのしっぽ", R.drawable.);
//		itemImageResource.put("くっつきバリ", R.drawable.);
		itemImageResource.put("くろいてっきゅう", R.drawable.ironball);
//		itemImageResource.put("でんきだま", R.drawable.);
//		itemImageResource.put("ふといホネ", R.drawable.);
//		itemImageResource.put("こころのしずく", R.drawable.);
//		itemImageResource.put("はっきんだま", R.drawable.);
//		itemImageResource.put("しらたま", R.drawable.);
//		itemImageResource.put("こんごうだま", R.drawable.);
//		itemImageResource.put("しんかいのキバ", R.drawable.);
//		itemImageResource.put("しんかいのウロコ", R.drawable.);
//		itemImageResource.put("ながねぎ", R.drawable.);
//		itemImageResource.put("ラッキーパンチ", R.drawable.);
//		itemImageResource.put("スピードパウダー", R.drawable.);
//		itemImageResource.put("メタルパウダー", R.drawable.);
		itemImageResource.put("じゃくてんほけん", R.drawable.weaknesspolicy);
		itemImageResource.put("とつげきチョッキ", R.drawable.assaultvest);
		itemImageResource.put("ぼうじんゴーグル", R.drawable.safetygoggles);
//		itemImageResource.put("あかいいと", R.drawable.);
//		itemImageResource.put("アップグレード", R.drawable.);
//		itemImageResource.put("あやしいおこう", R.drawable.);
//		itemImageResource.put("あやしいパッチ", R.drawable.);
//		itemImageResource.put("うしおのおこう", R.drawable.);
//		itemImageResource.put("エレキブースター", R.drawable.);
//		itemImageResource.put("おうじゃのしるし", R.drawable.);
//		itemImageResource.put("おおきなねっこ", R.drawable.);
//		itemImageResource.put("おはなのおこう", R.drawable.);
//		itemImageResource.put("おまもりこばん", R.drawable.);
//		itemImageResource.put("かいがらのすず", R.drawable.);
//		itemImageResource.put("かるいし", R.drawable.);
//		itemImageResource.put("かわらずのいし", R.drawable.);
//		itemImageResource.put("がんせきおこう", R.drawable.);
//		itemImageResource.put("きあいのハチマキ", R.drawable.);
//		itemImageResource.put("きゅうこん", R.drawable.);
//		itemImageResource.put("きょうせいギプス", R.drawable.);
//		itemImageResource.put("きよめのおこう", R.drawable.);
//		itemImageResource.put("きよめのおふだ", R.drawable.);
//		itemImageResource.put("きれいなウロコ", R.drawable.);
//		itemImageResource.put("けむりだま", R.drawable.);
//		itemImageResource.put("こううんのおこう", R.drawable.);
		itemImageResource.put("ゴツゴツメット", R.drawable.rockyhelmet);
//		itemImageResource.put("さざなみのおこう", R.drawable.);
//		itemImageResource.put("しあわせタマゴ", R.drawable.);
//		itemImageResource.put("しめつけバンド", R.drawable.);
//		itemImageResource.put("じゅうでんち", R.drawable.);
//		itemImageResource.put("しんかのきせき", R.drawable.);
//		itemImageResource.put("だっしゅつボタン", R.drawable.);
//		itemImageResource.put("においぶくろ", R.drawable.);
//		itemImageResource.put("ねらいのまと", R.drawable.);
//		itemImageResource.put("ひかりごけ", R.drawable.);
//		itemImageResource.put("ふうせん", R.drawable.);
//		itemImageResource.put("プロテクター", R.drawable.);
//		itemImageResource.put("ホイップポップ", R.drawable.);
//		itemImageResource.put("マグマブースター", R.drawable.);
//		itemImageResource.put("まんぷくおこう", R.drawable.);
//		itemImageResource.put("やすらぎのすず", R.drawable.);
//		itemImageResource.put("ゆきだま", R.drawable.);
//		itemImageResource.put("りゅうのウロコ", R.drawable.);
//		itemImageResource.put("れいかいのぬの", R.drawable.);
//		itemImageResource.put("レッドカード", R.drawable.);
//		itemImageResource.put("アクアカセット", R.drawable.);
//		itemImageResource.put("イナズマカセット", R.drawable.);
//		itemImageResource.put("こころのしずく", R.drawable.);
//		itemImageResource.put("スピードパウダー", R.drawable.);
//		itemImageResource.put("フリーズカセット", R.drawable.);
//		itemImageResource.put("ブレイズカセット", R.drawable.);
//		itemImageResource.put("シルクのスカーフ", R.drawable.);
//		itemImageResource.put("もくたん", R.drawable.);
//		itemImageResource.put("しんぴのしずく", R.drawable.);
//		itemImageResource.put("じしゃく", R.drawable.);
//		itemImageResource.put("きせきのタネ", R.drawable.);
//		itemImageResource.put("とけないこおり", R.drawable.);
//		itemImageResource.put("くろおび", R.drawable.);
//		itemImageResource.put("どくバリ", R.drawable.);
//		itemImageResource.put("やわらかいすな", R.drawable.);
//		itemImageResource.put("するどいくちばし", R.drawable.);
//		itemImageResource.put("まがったスプーン", R.drawable.);
//		itemImageResource.put("ぎんのこな", R.drawable.);
//		itemImageResource.put("かたいいし", R.drawable.);
//		itemImageResource.put("のろいのおふだ", R.drawable.);
//		itemImageResource.put("りゅうのキバ", R.drawable.);
//		itemImageResource.put("くろいメガネ", R.drawable.);
//		itemImageResource.put("メタルコート", R.drawable.);
//		itemImageResource.put("ナイト", R.drawable.);

		pokemonImageResource = new HashMap<>();
		pokemonImageResource.put("003", R.drawable.n003);
		pokemonImageResource.put("006", R.drawable.n006);
		pokemonImageResource.put("009", R.drawable.n009);
		pokemonImageResource.put("012", R.drawable.n012);
		pokemonImageResource.put("015", R.drawable.n015);
		pokemonImageResource.put("018", R.drawable.n018);
		pokemonImageResource.put("024", R.drawable.n024);
		pokemonImageResource.put("026", R.drawable.n026);
		pokemonImageResource.put("028", R.drawable.n028);
		pokemonImageResource.put("031", R.drawable.n031);
		pokemonImageResource.put("034", R.drawable.n034);
		pokemonImageResource.put("036", R.drawable.n036);
		pokemonImageResource.put("038", R.drawable.n038);
		pokemonImageResource.put("040", R.drawable.n040);
		pokemonImageResource.put("042", R.drawable.n042);
		pokemonImageResource.put("045", R.drawable.n045);
		pokemonImageResource.put("049", R.drawable.n049);
		pokemonImageResource.put("051", R.drawable.n051);
		pokemonImageResource.put("053", R.drawable.n053);
		pokemonImageResource.put("055", R.drawable.n055);
		pokemonImageResource.put("057", R.drawable.n057);
		pokemonImageResource.put("059", R.drawable.n059);
		pokemonImageResource.put("062", R.drawable.n062);
		pokemonImageResource.put("065", R.drawable.n065);
		pokemonImageResource.put("068", R.drawable.n068);
		pokemonImageResource.put("071", R.drawable.n071);
		pokemonImageResource.put("073", R.drawable.n073);
		pokemonImageResource.put("076", R.drawable.n076);
		pokemonImageResource.put("078", R.drawable.n078);
		pokemonImageResource.put("080", R.drawable.n080);
		pokemonImageResource.put("082", R.drawable.n082);
		pokemonImageResource.put("083", R.drawable.n083);
		pokemonImageResource.put("085", R.drawable.n085);
		pokemonImageResource.put("087", R.drawable.n087);
		pokemonImageResource.put("089", R.drawable.n089);
		pokemonImageResource.put("091", R.drawable.n091);
		pokemonImageResource.put("094", R.drawable.n094);
		pokemonImageResource.put("095", R.drawable.n095);
		pokemonImageResource.put("097", R.drawable.n097);
		pokemonImageResource.put("099", R.drawable.n099);
		pokemonImageResource.put("101", R.drawable.n101);
		pokemonImageResource.put("103", R.drawable.n103);
		pokemonImageResource.put("105", R.drawable.n105);
		pokemonImageResource.put("106", R.drawable.n106);
		pokemonImageResource.put("107", R.drawable.n107);
		pokemonImageResource.put("110", R.drawable.n110);
		pokemonImageResource.put("113", R.drawable.n113);
		pokemonImageResource.put("114", R.drawable.n114);
		pokemonImageResource.put("115", R.drawable.n115);
		pokemonImageResource.put("119", R.drawable.n119);
		pokemonImageResource.put("121", R.drawable.n121);
		pokemonImageResource.put("123", R.drawable.n123);
		pokemonImageResource.put("124", R.drawable.n124);
		pokemonImageResource.put("125", R.drawable.n125);
		pokemonImageResource.put("126", R.drawable.n126);
		pokemonImageResource.put("127", R.drawable.n127);
		pokemonImageResource.put("128", R.drawable.n128);
		pokemonImageResource.put("130", R.drawable.n130);
		pokemonImageResource.put("131", R.drawable.n131);
		pokemonImageResource.put("132", R.drawable.n132);
		pokemonImageResource.put("134", R.drawable.n134);
		pokemonImageResource.put("135", R.drawable.n135);
		pokemonImageResource.put("136", R.drawable.n136);
		pokemonImageResource.put("139", R.drawable.n139);
		pokemonImageResource.put("141", R.drawable.n141);
		pokemonImageResource.put("142", R.drawable.n142);
		pokemonImageResource.put("143", R.drawable.n143);
		pokemonImageResource.put("144", R.drawable.n144);
		pokemonImageResource.put("145", R.drawable.n145);
		pokemonImageResource.put("146", R.drawable.n146);
		pokemonImageResource.put("148", R.drawable.n148);
		pokemonImageResource.put("149", R.drawable.n149);
		pokemonImageResource.put("154", R.drawable.n154);
		pokemonImageResource.put("157", R.drawable.n157);
		pokemonImageResource.put("160", R.drawable.n160);
		pokemonImageResource.put("161", R.drawable.n161);
		pokemonImageResource.put("164", R.drawable.n164);
		pokemonImageResource.put("166", R.drawable.n166);
		pokemonImageResource.put("168", R.drawable.n168);
		pokemonImageResource.put("169", R.drawable.n169);
		pokemonImageResource.put("171", R.drawable.n171);
		pokemonImageResource.put("178", R.drawable.n178);
		pokemonImageResource.put("181", R.drawable.n181);
		pokemonImageResource.put("184", R.drawable.n184);
		pokemonImageResource.put("185", R.drawable.n185);
		pokemonImageResource.put("186", R.drawable.n186);
		pokemonImageResource.put("189", R.drawable.n189);
		pokemonImageResource.put("192", R.drawable.n192);
		pokemonImageResource.put("195", R.drawable.n195);
		pokemonImageResource.put("196", R.drawable.n196);
		pokemonImageResource.put("198", R.drawable.n198);
		pokemonImageResource.put("197", R.drawable.n197);
		pokemonImageResource.put("199", R.drawable.n199);
		pokemonImageResource.put("210", R.drawable.n210);
		pokemonImageResource.put("200", R.drawable.n200);
		pokemonImageResource.put("202", R.drawable.n202);
		pokemonImageResource.put("203", R.drawable.n203);
		pokemonImageResource.put("205", R.drawable.n205);
		pokemonImageResource.put("208", R.drawable.n208);
		pokemonImageResource.put("210", R.drawable.n210);
		pokemonImageResource.put("212", R.drawable.n212);
		pokemonImageResource.put("213", R.drawable.n213);
		pokemonImageResource.put("214", R.drawable.n214);
		pokemonImageResource.put("217", R.drawable.n217);
		pokemonImageResource.put("219", R.drawable.n219);
		pokemonImageResource.put("221", R.drawable.n221);
		pokemonImageResource.put("224", R.drawable.n224);
		pokemonImageResource.put("225", R.drawable.n225);
		pokemonImageResource.put("226", R.drawable.n226);
		pokemonImageResource.put("227", R.drawable.n227);
		pokemonImageResource.put("229", R.drawable.n229);
		pokemonImageResource.put("230", R.drawable.n230);
		pokemonImageResource.put("232", R.drawable.n232);
		pokemonImageResource.put("233", R.drawable.n233);
		pokemonImageResource.put("234", R.drawable.n234);
		pokemonImageResource.put("235", R.drawable.n235);
		pokemonImageResource.put("237", R.drawable.n237);
		pokemonImageResource.put("241", R.drawable.n241);
		pokemonImageResource.put("242", R.drawable.n242);
		pokemonImageResource.put("243", R.drawable.n243);
		pokemonImageResource.put("244", R.drawable.n244);
		pokemonImageResource.put("245", R.drawable.n245);
		pokemonImageResource.put("248", R.drawable.n248);
		pokemonImageResource.put("254", R.drawable.n254);
		pokemonImageResource.put("257", R.drawable.n257);
		pokemonImageResource.put("260", R.drawable.n260);
		pokemonImageResource.put("262", R.drawable.n262);
		pokemonImageResource.put("264", R.drawable.n264);
		pokemonImageResource.put("267", R.drawable.n267);
		pokemonImageResource.put("269", R.drawable.n269);
		pokemonImageResource.put("272", R.drawable.n272);
		pokemonImageResource.put("275", R.drawable.n275);
		pokemonImageResource.put("277", R.drawable.n277);
		pokemonImageResource.put("279", R.drawable.n279);
		pokemonImageResource.put("282", R.drawable.n282);
		pokemonImageResource.put("286", R.drawable.n286);
		pokemonImageResource.put("289", R.drawable.n289);
		pokemonImageResource.put("295", R.drawable.n295);
		pokemonImageResource.put("291", R.drawable.n291);
		pokemonImageResource.put("292", R.drawable.n292);
		pokemonImageResource.put("295", R.drawable.n295);
		pokemonImageResource.put("297", R.drawable.n297);
		pokemonImageResource.put("286", R.drawable.n286);
		pokemonImageResource.put("301", R.drawable.n301);
		pokemonImageResource.put("302", R.drawable.n302);
		pokemonImageResource.put("303", R.drawable.n303);
		pokemonImageResource.put("306", R.drawable.n306);
		pokemonImageResource.put("308", R.drawable.n308);
		pokemonImageResource.put("310", R.drawable.n310);
		pokemonImageResource.put("317", R.drawable.n317);
		pokemonImageResource.put("319", R.drawable.n319);
		pokemonImageResource.put("321", R.drawable.n321);
		pokemonImageResource.put("323", R.drawable.n323);
		pokemonImageResource.put("324", R.drawable.n324);
		pokemonImageResource.put("326", R.drawable.n326);
		pokemonImageResource.put("330", R.drawable.n330);
		pokemonImageResource.put("332", R.drawable.n332);
		pokemonImageResource.put("334", R.drawable.n334);
		pokemonImageResource.put("335", R.drawable.n335);
		pokemonImageResource.put("336", R.drawable.n336);
		pokemonImageResource.put("337", R.drawable.n337);
		pokemonImageResource.put("338", R.drawable.n338);
		pokemonImageResource.put("340", R.drawable.n340);
		pokemonImageResource.put("342", R.drawable.n342);
		pokemonImageResource.put("344", R.drawable.n344);
		pokemonImageResource.put("346", R.drawable.n346);
		pokemonImageResource.put("348", R.drawable.n348);
		pokemonImageResource.put("350", R.drawable.n350);
		pokemonImageResource.put("354", R.drawable.n354);
		pokemonImageResource.put("356", R.drawable.n356);
		pokemonImageResource.put("359", R.drawable.n359);
		pokemonImageResource.put("362", R.drawable.n362);
		pokemonImageResource.put("365", R.drawable.n365);
		pokemonImageResource.put("367", R.drawable.n367);
		pokemonImageResource.put("368", R.drawable.n368);
		pokemonImageResource.put("369", R.drawable.n369);
		pokemonImageResource.put("373", R.drawable.n373);
		pokemonImageResource.put("376", R.drawable.n376);
		pokemonImageResource.put("380", R.drawable.n380);
		pokemonImageResource.put("381", R.drawable.n381);
		pokemonImageResource.put("389", R.drawable.n389);
		pokemonImageResource.put("392", R.drawable.n392);
		pokemonImageResource.put("395", R.drawable.n395);
		pokemonImageResource.put("398", R.drawable.n398);
		pokemonImageResource.put("423", R.drawable.n423);
		pokemonImageResource.put("426", R.drawable.n426);
		pokemonImageResource.put("428", R.drawable.n428);
		pokemonImageResource.put("429", R.drawable.n429);
		pokemonImageResource.put("430", R.drawable.n430);
		pokemonImageResource.put("432", R.drawable.n432);
		pokemonImageResource.put("445", R.drawable.n445);
		pokemonImageResource.put("448", R.drawable.n448);
		pokemonImageResource.put("450", R.drawable.n450);
		pokemonImageResource.put("452", R.drawable.n452);
		pokemonImageResource.put("454", R.drawable.n454);
		pokemonImageResource.put("460", R.drawable.n460);
		pokemonImageResource.put("462", R.drawable.n462);
		pokemonImageResource.put("463", R.drawable.n463);
		pokemonImageResource.put("464", R.drawable.n464);
		pokemonImageResource.put("465", R.drawable.n465);
		pokemonImageResource.put("468", R.drawable.n468);
		pokemonImageResource.put("472", R.drawable.n472);
		pokemonImageResource.put("473", R.drawable.n473);
		pokemonImageResource.put("485", R.drawable.n485);
		pokemonImageResource.put("488", R.drawable.n488);
		pokemonImageResource.put("512", R.drawable.n512);
		pokemonImageResource.put("514", R.drawable.n514);
		pokemonImageResource.put("516", R.drawable.n516);
		pokemonImageResource.put("523", R.drawable.n523);
		pokemonImageResource.put("526", R.drawable.n526);
		pokemonImageResource.put("530", R.drawable.n530);
		pokemonImageResource.put("534", R.drawable.n534);
		pokemonImageResource.put("545", R.drawable.n545);
		pokemonImageResource.put("547", R.drawable.n547);
		pokemonImageResource.put("549", R.drawable.n549);
		pokemonImageResource.put("553", R.drawable.n553);
		pokemonImageResource.put("555", R.drawable.n555);
		pokemonImageResource.put("558", R.drawable.n558);
		pokemonImageResource.put("560", R.drawable.n560);
		pokemonImageResource.put("561", R.drawable.n561);
		pokemonImageResource.put("565", R.drawable.n565);
		pokemonImageResource.put("567", R.drawable.n567);
		pokemonImageResource.put("569", R.drawable.n569);
		pokemonImageResource.put("571", R.drawable.n571);
		pokemonImageResource.put("573", R.drawable.n573);
		pokemonImageResource.put("576", R.drawable.n576);
		pokemonImageResource.put("579", R.drawable.n579);
		pokemonImageResource.put("581", R.drawable.n581);
		pokemonImageResource.put("584", R.drawable.n584);
		pokemonImageResource.put("586", R.drawable.n586);
		pokemonImageResource.put("587", R.drawable.n587);
		pokemonImageResource.put("589", R.drawable.n589);
		pokemonImageResource.put("591", R.drawable.n591);
		pokemonImageResource.put("593", R.drawable.n593);
		pokemonImageResource.put("594", R.drawable.n594);
		pokemonImageResource.put("596", R.drawable.n596);
		pokemonImageResource.put("598", R.drawable.n598);
		pokemonImageResource.put("601", R.drawable.n601);
		pokemonImageResource.put("604", R.drawable.n604);
		pokemonImageResource.put("606", R.drawable.n606);
		pokemonImageResource.put("609", R.drawable.n609);
		pokemonImageResource.put("612", R.drawable.n612);
		pokemonImageResource.put("614", R.drawable.n614);
		pokemonImageResource.put("615", R.drawable.n615);
		pokemonImageResource.put("617", R.drawable.n617);
		pokemonImageResource.put("620", R.drawable.n620);
		pokemonImageResource.put("621", R.drawable.n621);
		pokemonImageResource.put("623", R.drawable.n623);
		pokemonImageResource.put("625", R.drawable.n625);
		pokemonImageResource.put("626", R.drawable.n626);
		pokemonImageResource.put("628", R.drawable.n628);
		pokemonImageResource.put("630", R.drawable.n630);
		pokemonImageResource.put("631", R.drawable.n631);
		pokemonImageResource.put("632", R.drawable.n632);
		pokemonImageResource.put("635", R.drawable.n635);
		pokemonImageResource.put("637", R.drawable.n637);
		pokemonImageResource.put("638", R.drawable.n638);
		pokemonImageResource.put("639", R.drawable.n639);
		pokemonImageResource.put("640", R.drawable.n640);
		pokemonImageResource.put("641", R.drawable.n641);
		pokemonImageResource.put("641-1", R.drawable.n641_2);
		pokemonImageResource.put("642", R.drawable.n642);
		pokemonImageResource.put("642-1", R.drawable.n642_2);
		pokemonImageResource.put("645", R.drawable.n645);
		pokemonImageResource.put("645-1", R.drawable.n645_2);
		pokemonImageResource.put("651", R.drawable.n651);
		pokemonImageResource.put("655", R.drawable.n655);
		pokemonImageResource.put("658", R.drawable.n658);
		pokemonImageResource.put("660", R.drawable.n660);
		pokemonImageResource.put("663", R.drawable.n663);
		pokemonImageResource.put("666", R.drawable.n666);
		pokemonImageResource.put("668", R.drawable.n668);
		pokemonImageResource.put("673", R.drawable.n673);
		pokemonImageResource.put("675", R.drawable.n675);
		pokemonImageResource.put("676", R.drawable.n676);
		pokemonImageResource.put("678", R.drawable.n678);
		pokemonImageResource.put("681", R.drawable.n681);
		pokemonImageResource.put("683", R.drawable.n683);
		pokemonImageResource.put("685", R.drawable.n685);
		pokemonImageResource.put("687", R.drawable.n687);
		pokemonImageResource.put("689", R.drawable.n689);
		pokemonImageResource.put("691", R.drawable.n691);
		pokemonImageResource.put("693", R.drawable.n693);
		pokemonImageResource.put("695", R.drawable.n695);
		pokemonImageResource.put("697", R.drawable.n697);
		pokemonImageResource.put("699", R.drawable.n699);
		pokemonImageResource.put("700", R.drawable.n700);
		pokemonImageResource.put("701", R.drawable.n701);
		pokemonImageResource.put("702", R.drawable.n702);
		pokemonImageResource.put("703", R.drawable.n703);
		pokemonImageResource.put("706", R.drawable.n706);
		pokemonImageResource.put("707", R.drawable.n707);
		pokemonImageResource.put("709", R.drawable.n709);
		pokemonImageResource.put("700", R.drawable.n700);
		pokemonImageResource.put("711", R.drawable.n711);
		pokemonImageResource.put("713", R.drawable.n713);
		pokemonImageResource.put("715", R.drawable.n715);
		pokemonImageResource.put("112", R.drawable.n112);
		pokemonImageResource.put("211", R.drawable.n211);
		pokemonImageResource.put("222", R.drawable.n222);
		pokemonImageResource.put("025", R.drawable.n25);
		pokemonImageResource.put("284", R.drawable.n284);
		pokemonImageResource.put("311", R.drawable.n311);
		pokemonImageResource.put("312", R.drawable.n312);
		pokemonImageResource.put("313", R.drawable.n313);
		pokemonImageResource.put("314", R.drawable.n314);
		pokemonImageResource.put("327", R.drawable.n327);
		pokemonImageResource.put("351", R.drawable.n351);
		pokemonImageResource.put("352", R.drawable.n352);
		pokemonImageResource.put("357", R.drawable.n357);
		pokemonImageResource.put("358", R.drawable.n358);
		pokemonImageResource.put("370", R.drawable.n370);
		pokemonImageResource.put("377", R.drawable.n377);
		pokemonImageResource.put("378", R.drawable.n378);
		pokemonImageResource.put("379", R.drawable.n379);
		pokemonImageResource.put("400", R.drawable.n400);
		pokemonImageResource.put("402", R.drawable.n402);
		pokemonImageResource.put("405", R.drawable.n405);
		pokemonImageResource.put("407", R.drawable.n407);
		pokemonImageResource.put("408", R.drawable.n408);
		pokemonImageResource.put("411", R.drawable.n411);
		pokemonImageResource.put("413", R.drawable.n413);
		pokemonImageResource.put("414", R.drawable.n414);
		pokemonImageResource.put("416", R.drawable.n416);
		pokemonImageResource.put("417", R.drawable.n417);
		pokemonImageResource.put("419", R.drawable.n419);
		pokemonImageResource.put("419", R.drawable.n419);
		pokemonImageResource.put("421", R.drawable.n421);
		pokemonImageResource.put("424", R.drawable.n424);
		pokemonImageResource.put("435", R.drawable.n435);
		pokemonImageResource.put("437", R.drawable.n437);
		pokemonImageResource.put("441", R.drawable.n441);
		pokemonImageResource.put("442", R.drawable.n442);
		pokemonImageResource.put("445", R.drawable.n445);
		pokemonImageResource.put("461", R.drawable.n461);
		pokemonImageResource.put("466", R.drawable.n466);
		pokemonImageResource.put("467", R.drawable.n467);
		pokemonImageResource.put("469", R.drawable.n469);
		pokemonImageResource.put("47", R.drawable.n47);
		pokemonImageResource.put("470", R.drawable.n470);
		pokemonImageResource.put("471", R.drawable.n471);
		pokemonImageResource.put("474", R.drawable.n474);
		pokemonImageResource.put("475", R.drawable.n475);
		pokemonImageResource.put("476", R.drawable.n476);
		pokemonImageResource.put("477", R.drawable.n477);
		pokemonImageResource.put("478", R.drawable.n478);
		pokemonImageResource.put("479-1", R.drawable.n479_2);
		pokemonImageResource.put("479-2", R.drawable.n479_3);
		pokemonImageResource.put("479-3", R.drawable.n479_4);
		pokemonImageResource.put("479-4", R.drawable.n479_5);
		pokemonImageResource.put("479-5", R.drawable.n479_6);
		pokemonImageResource.put("480", R.drawable.n480);
		pokemonImageResource.put("481", R.drawable.n481);
		pokemonImageResource.put("482", R.drawable.n482);
		pokemonImageResource.put("486", R.drawable.n486);
		pokemonImageResource.put("497", R.drawable.n497);
		pokemonImageResource.put("500", R.drawable.n500);
		pokemonImageResource.put("503", R.drawable.n503);
		pokemonImageResource.put("505", R.drawable.n505);
		pokemonImageResource.put("508", R.drawable.n508);
		pokemonImageResource.put("510", R.drawable.n510);
		pokemonImageResource.put("518", R.drawable.n518);
		pokemonImageResource.put("528", R.drawable.n528);
		pokemonImageResource.put("531", R.drawable.n531);
		pokemonImageResource.put("537", R.drawable.n537);
		pokemonImageResource.put("538", R.drawable.n538);
		pokemonImageResource.put("539", R.drawable.n539);
		pokemonImageResource.put("542", R.drawable.n542);
		pokemonImageResource.put("550", R.drawable.n550);
		pokemonImageResource.put("556", R.drawable.n556);
		pokemonImageResource.put("563", R.drawable.n563);
		pokemonImageResource.put("618", R.drawable.n618);
		pokemonImageResource.put("521", R.drawable.n521);
		
		//XY Mega Revolution
		pokemonImageResource.put("003mx", R.drawable.n003_mega);
		pokemonImageResource.put("006mx", R.drawable.n006_megax);
		pokemonImageResource.put("006my", R.drawable.n006_megay);
		pokemonImageResource.put("009mx", R.drawable.n009_mega);
		pokemonImageResource.put("065mx", R.drawable.n065_mega);
		pokemonImageResource.put("094mx", R.drawable.n094_mega);
		pokemonImageResource.put("115mx", R.drawable.n115_mega);
		pokemonImageResource.put("127mx", R.drawable.n127_mega);
		pokemonImageResource.put("130mx", R.drawable.n130_mega);
		pokemonImageResource.put("142mx", R.drawable.n142_mega);
		pokemonImageResource.put("181mx", R.drawable.n181_mega);
		pokemonImageResource.put("212mx", R.drawable.n212_mega);
		pokemonImageResource.put("214mx", R.drawable.n214_mega);
		pokemonImageResource.put("229mx", R.drawable.n229_mega);
		pokemonImageResource.put("248mx", R.drawable.n248_mega);
		pokemonImageResource.put("257mx", R.drawable.n257_mega);
		pokemonImageResource.put("282mx", R.drawable.n282_mega);
		pokemonImageResource.put("303mx", R.drawable.n303_mega);
		pokemonImageResource.put("306mx", R.drawable.n306_mega);
		pokemonImageResource.put("308mx", R.drawable.n308_mega);
		pokemonImageResource.put("310mx", R.drawable.n310_mega);
		pokemonImageResource.put("354mx", R.drawable.n354_mega);
		pokemonImageResource.put("359mx", R.drawable.n359_mega);
		pokemonImageResource.put("445mx", R.drawable.n445_mega);
		pokemonImageResource.put("460mx", R.drawable.n460_mega);
		pokemonImageResource.put("448mx", R.drawable.n448_mega);

        //ORAS Mega Revolution
        pokemonImageResource.put("015mx", R.drawable.n015_mega);
        pokemonImageResource.put("018mx", R.drawable.n018_mega);
        pokemonImageResource.put("080mx", R.drawable.n080_mega);
        pokemonImageResource.put("208mx", R.drawable.n208_mega);
        pokemonImageResource.put("254mx", R.drawable.n254_mega);
        pokemonImageResource.put("260mx", R.drawable.n260_mega);
        pokemonImageResource.put("302mx", R.drawable.n302_mega);
        pokemonImageResource.put("319mx", R.drawable.n319_mega);
        pokemonImageResource.put("323mx", R.drawable.n323_mega);
        pokemonImageResource.put("334mx", R.drawable.n334_mega);
        pokemonImageResource.put("362mx", R.drawable.n362_mega);
        pokemonImageResource.put("373mx", R.drawable.n373_mega);
        pokemonImageResource.put("376mx", R.drawable.n376_mega);
        pokemonImageResource.put("380mx", R.drawable.n380_mega);
        pokemonImageResource.put("381mx", R.drawable.n381_mega);
        pokemonImageResource.put("428mx", R.drawable.n428_mega);
        pokemonImageResource.put("475mx", R.drawable.n475_mega);
        pokemonImageResource.put("531mx", R.drawable.n531_mega);
	}

    public static Bitmap createImage(PBAPokemon p, float scale, Resources resource){
        Bitmap image = BitmapFactory.decodeResource(resource, p.getResourceId());
        if(image == null){
            Log.e("createImage", p.getJname() + " - " + p.getResourceId());
            return null;
        }
        Matrix matrix = new Matrix();
        matrix.postScale(scale / (float)image.getWidth(), scale / (float)image.getHeight());
        image = Bitmap.createBitmap(image, 0, 0, image.getWidth(),image.getHeight(), matrix, true);
        return image;
    }

	public static Bitmap createImage(int resourceId, float scale, Resources resource){
		Bitmap image = BitmapFactory.decodeResource(resource, resourceId);
		Matrix matrix = new Matrix();
		matrix.postScale(scale / (float)image.getWidth(), scale / (float)image.getHeight());
		image = Bitmap.createBitmap(image, 0, 0, image.getWidth(),image.getHeight(), matrix, true);
		return image;
	}

}

